---
## This playbook doesn't have a password so we would need to use:
## ansible-playbook mac_playbook.yml -u patryk -k to run it
## to look for a specific ip: ansible-playbook mac_playbook.yml -u patryk -k | grep "ok: \|1\.203"

- name: Get MAC information
  hosts: all
  gather_facts: false

  tasks:
    - name: show mac address-table
      raw: "show mac address-table"

      register: print_output

    - debug: var=print_output.stdout_lines
