---
- name: Manage GNS3 devices
  hosts: [Cisco-Core]
  gather_facts: false
  connection: local

  vars:
    cli:
      username: patryk
      password: cisco
      #transport: cli     ## Transport CLI is obsolete


  tasks:
    - name: enable ospf
      ios_config:              ## With ios_config module we don't use stdout_lines
        provider: "{{ cli }}"
        authorize: yes
        parents: router ospf 1
        lines:
          - network 0.0.0.0 255.255.255.255 area 0

      register: print_output

    - debug: var=print_output

- name: Switch specific config
  hosts: S1
  gather_facts: false
  connection: local

  vars:
    cli:
      username: patryk
      password: cisco

  tasks:
    - name: Create VLANs
      ios_config:             ## With ios_config module we don't use stdout_lines
        provider: "{{ cli }}"
        authorize: yes
        lines:
          - vlan 2-5

      register: print_output

    - debug: var=print_output
